import './components/page.js'
import './components/row.js'
import './components/column.js'
import './components/main.js'
import './components/map-component.js'
import './components/prompt.js'
import './components/list.js'
import './components/not-found.js'
